version: '3'

services:
  angular-frontend:
    container_name: angular-frontend
    build: ../frontend
    ports:
      - '4200:4200'
    volumes:
      - ../frontend/node_modules:/frontend/node_modules
      - ../frontend/src:/frontend/src
      - ../frontend/angular.json:/frontend/angular.json
      - ../frontend/package.json:/frontend/package.json
      - ../frontend/package-lock.json:/frontend/package-lock.json
      - ../frontend/tsconfig.app.json:/frontend/tsconfig.app.json
      - ../frontend/tsconfig.json:/frontend/tsconfig.json
      - ../frontend/tsconfig.spec.json:/frontend/tsconfig.spec.json
    restart: always
  node-backend:
    container_name: node-backend
    build: ../backend
    depends_on:
      - db
    ports:
      - '9000:9000'
    volumes:
      - ../backend/dist:/backend/dist
      - ../backend/node_modules:/backend/node_modules
      - ../backend/src:/backend/src
      - ../backend/nest-cli.json:/backend/nest-cli.json
      - ../backend/package.json:/backend/package.json
      - ../backend/package-lock.json:/backend/package-lock.json
      - ../backend/tsconfig.build.json:/backend/tsconfig.build.json
      - ../backend/tsconfig.json:/backend/tsconfig.json

    restart: always
    links:
      - db
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.5
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: none
volumes:
  local_pgdata:
  pgadmin-data: